/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package starprogrammers;

public class App {

    public static void main(String[] args) {
        Hotel testHotel = new Hotel();
    }
}
