/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package starprogrammers;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.*;

import java.sql.SQLException;
import java.time.LocalDate;


class AppTest {
  @Test
  void mySqlConnectorConnects() throws SQLException {
    assertNotNull(MysqlConnector.getConnection());
  } 
  @Test
  void hotelGetOccupiedRoomsTest(){
    Room testRoom = new Room("lastName", "firstName", 989, "Suite", "King", 1, 1000, 1);
    RoomDataBase.insertRoom(testRoom);
    assertEquals(1, Hotel.getReservedRooms().size(), "The only occupied room is testRoom");
    RoomDataBase.removeRoomFromTable(989);

  }
  @Test
  void hotelGetOccupiedRoomsTestElse(){
    assertEquals(0, Hotel.getReservedRooms().size(), "Rooms with null names are unoccupied, 0 rooms occupied.");
  }
}
