/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package starprogrammers;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.*;

import java.sql.SQLException;


class AppTest {
  @Test
  void mySqlConnectorConnects() throws SQLException {
    assertNotNull(MysqlConnector.getConnection());
  } 
}
